
#include <stdint.h>
#include "mini_trackpad_iqs7211e_init.h"

#define IQS7211E_MM_ALP_ATI_COMP_A 0x1F
#define IQS7211E_MM_TP_GLOBAL_MIRRORS 0x21
#define IQS7211E_MM_ACTIVE_MODE_RR 0x28
#define IQS7211E_MM_SYS_CONTROL 0x33
#define IQS7211E_MM_ALP_SETUP 0x36
#define IQS7211E_MM_TP_TOUCH_SET_CLEAR_THR 0x38
#define IQS7211E_MM_LP1_FILTERS 0x3B
#define IQS7211E_MM_TP_CONV_FREQ 0x3D
#define IQS7211E_MM_TP_RX_SETTINGS 0x41
#define IQS7211E_MM_SETTINGS_VERSION 0x4A
#define IQS7211E_MM_GESTURE_ENABLE 0x4B
#define IQS7211E_MM_RX_TX_MAPPING_0_1 0x56
#define IQS7211E_MM_PROXA_CYCLE0 0x5D
#define IQS7211E_MM_PROXA_CYCLE10 0x6C
#define IQS7211E_MM_PROXA_CYCLE20 0x7B

const uint8_t mini_trackpad_iqs7211e_init[] = {
    IQS7211E_MM_ALP_ATI_COMP_A, 4, ALP_COMPENSATION_A_0, ALP_COMPENSATION_A_1, ALP_COMPENSATION_B_0, ALP_COMPENSATION_B_1,
    IQS7211E_MM_TP_GLOBAL_MIRRORS, 14, TP_ATI_MULTIPLIERS_DIVIDERS_0, TP_ATI_MULTIPLIERS_DIVIDERS_1, TP_COMPENSATION_DIV, TP_REF_DRIFT_LIMIT, TP_ATI_TARGET_0, TP_ATI_TARGET_1, TP_MIN_COUNT_REATI_0, TP_MIN_COUNT_REATI_1, ALP_ATI_MULTIPLIERS_DIVIDERS_0, ALP_ATI_MULTIPLIERS_DIVIDERS_1, ALP_COMPENSATION_DIV, ALP_LTA_DRIFT_LIMIT, ALP_ATI_TARGET_0, ALP_ATI_TARGET_1,
    IQS7211E_MM_ACTIVE_MODE_RR, 22, ACTIVE_MODE_REPORT_RATE_0, ACTIVE_MODE_REPORT_RATE_1, IDLE_TOUCH_MODE_REPORT_RATE_0, IDLE_TOUCH_MODE_REPORT_RATE_1, IDLE_MODE_REPORT_RATE_0, IDLE_MODE_REPORT_RATE_1, LP1_MODE_REPORT_RATE_0, LP1_MODE_REPORT_RATE_1, LP2_MODE_REPORT_RATE_0, LP2_MODE_REPORT_RATE_1, ACTIVE_MODE_TIMEOUT_0, ACTIVE_MODE_TIMEOUT_1, IDLE_TOUCH_MODE_TIMEOUT_0, IDLE_TOUCH_MODE_TIMEOUT_1, IDLE_MODE_TIMEOUT_0, IDLE_MODE_TIMEOUT_1, LP1_MODE_TIMEOUT_0, LP1_MODE_TIMEOUT_1, REATI_RETRY_TIME, REF_UPDATE_TIME, I2C_TIMEOUT_0, I2C_TIMEOUT_1,
    IQS7211E_MM_SYS_CONTROL, 6, SYSTEM_CONTROL_0, SYSTEM_CONTROL_1, CONFIG_SETTINGS0, CONFIG_SETTINGS1, OTHER_SETTINGS_0, OTHER_SETTINGS_1,
    IQS7211E_MM_ALP_SETUP, 4, ALP_SETUP_0, ALP_SETUP_1, ALP_TX_ENABLE_0, ALP_TX_ENABLE_1,
    IQS7211E_MM_TP_TOUCH_SET_CLEAR_THR, 6, TRACKPAD_TOUCH_SET_THRESHOLD, TRACKPAD_TOUCH_CLEAR_THRESHOLD, ALP_THRESHOLD_0, ALP_THRESHOLD_1, ALP_SET_DEBOUNCE, ALP_CLEAR_DEBOUNCE,
    IQS7211E_MM_LP1_FILTERS, 4, ALP_COUNT_BETA_LP1, ALP_LTA_BETA_LP1, ALP_COUNT_BETA_LP2, ALP_LTA_BETA_LP2,
    IQS7211E_MM_TP_CONV_FREQ, 8, TP_CONVERSION_FREQUENCY_UP_PASS_LENGTH, TP_CONVERSION_FREQUENCY_FRACTION_VALUE, ALP_CONVERSION_FREQUENCY_UP_PASS_LENGTH, ALP_CONVERSION_FREQUENCY_FRACTION_VALUE, TRACKPAD_HARDWARE_SETTINGS_0, TRACKPAD_HARDWARE_SETTINGS_1, ALP_HARDWARE_SETTINGS_0, ALP_HARDWARE_SETTINGS_1,
    IQS7211E_MM_TP_RX_SETTINGS, 18, TRACKPAD_SETTINGS_0_0, TRACKPAD_SETTINGS_0_1, TRACKPAD_SETTINGS_1_0, TRACKPAD_SETTINGS_1_1, X_RESOLUTION_0, X_RESOLUTION_1, Y_RESOLUTION_0, Y_RESOLUTION_1, XY_DYNAMIC_FILTER_BOTTOM_SPEED_0, XY_DYNAMIC_FILTER_BOTTOM_SPEED_1, XY_DYNAMIC_FILTER_TOP_SPEED_0, XY_DYNAMIC_FILTER_TOP_SPEED_1, XY_DYNAMIC_FILTER_BOTTOM_BETA, XY_DYNAMIC_FILTER_STATIC_FILTER_BETA, STATIONARY_TOUCH_MOV_THRESHOLD, FINGER_SPLIT_FACTOR, X_TRIM_VALUE, Y_TRIM_VALUE,
    IQS7211E_MM_SETTINGS_VERSION, 2, MINOR_VERSION, MAJOR_VERSION,
    IQS7211E_MM_GESTURE_ENABLE, 22, GESTURE_ENABLE_0, GESTURE_ENABLE_1, TAP_TOUCH_TIME_0, TAP_TOUCH_TIME_1, TAP_WAIT_TIME_0, TAP_WAIT_TIME_1, TAP_DISTANCE_0, TAP_DISTANCE_1, HOLD_TIME_0, HOLD_TIME_1, SWIPE_TIME_0, SWIPE_TIME_1, SWIPE_X_DISTANCE_0, SWIPE_X_DISTANCE_1, SWIPE_Y_DISTANCE_0, SWIPE_Y_DISTANCE_1, SWIPE_X_CONS_DIST_0, SWIPE_X_CONS_DIST_1, SWIPE_Y_CONS_DIST_0, SWIPE_Y_CONS_DIST_1, SWIPE_ANGLE, PALM_THRESHOLD,
    IQS7211E_MM_RX_TX_MAPPING_0_1, 14, RX_TX_MAP_0, RX_TX_MAP_1, RX_TX_MAP_2, RX_TX_MAP_3, RX_TX_MAP_4, RX_TX_MAP_5, RX_TX_MAP_6, RX_TX_MAP_7, RX_TX_MAP_8, RX_TX_MAP_9, RX_TX_MAP_10, RX_TX_MAP_11, RX_TX_MAP_12, RX_TX_MAP_FILLER,
    IQS7211E_MM_PROXA_CYCLE0, 30, PLACEHOLDER_0, CH_1_CYCLE_0, CH_2_CYCLE_0, PLACEHOLDER_1, CH_1_CYCLE_1, CH_2_CYCLE_1, PLACEHOLDER_2, CH_1_CYCLE_2, CH_2_CYCLE_2, PLACEHOLDER_3, CH_1_CYCLE_3, CH_2_CYCLE_3, PLACEHOLDER_4, CH_1_CYCLE_4, CH_2_CYCLE_4, PLACEHOLDER_5, CH_1_CYCLE_5, CH_2_CYCLE_5, PLACEHOLDER_6, CH_1_CYCLE_6, CH_2_CYCLE_6, PLACEHOLDER_7, CH_1_CYCLE_7, CH_2_CYCLE_7, PLACEHOLDER_8, CH_1_CYCLE_8, CH_2_CYCLE_8, PLACEHOLDER_9, CH_1_CYCLE_9, CH_2_CYCLE_9,
    IQS7211E_MM_PROXA_CYCLE10, 30, PLACEHOLDER_10, CH_1_CYCLE_10, CH_2_CYCLE_10, PLACEHOLDER_11, CH_1_CYCLE_11, CH_2_CYCLE_11, PLACEHOLDER_12, CH_1_CYCLE_12, CH_2_CYCLE_12, PLACEHOLDER_13, CH_1_CYCLE_13, CH_2_CYCLE_13, PLACEHOLDER_14, CH_1_CYCLE_14, CH_2_CYCLE_14, PLACEHOLDER_15, CH_1_CYCLE_15, CH_2_CYCLE_15, PLACEHOLDER_16, CH_1_CYCLE_16, CH_2_CYCLE_16, PLACEHOLDER_17, CH_1_CYCLE_17, CH_2_CYCLE_17, PLACEHOLDER_18, CH_1_CYCLE_18, CH_2_CYCLE_18, PLACEHOLDER_19, CH_1_CYCLE_19, CH_2_CYCLE_19,
    IQS7211E_MM_PROXA_CYCLE20, 3, PLACEHOLDER_20, CH_1_CYCLE_20, CH_2_CYCLE_20
};
